
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
	- namespace.yml
	- deployment.yml
	- service.yml
	- ingress.yml

configMapGenerator:
	- name: url-shortener-config
		literals:
			- PORT=8080
			- LOG_LEVEL=info

images:
	- name: ghcr.io/example/url-shortener
    newName: arturcampos/app
		newTag: latest
